version: "3.9"

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./movies.db}
      - TMDB_API_KEY=${TMDB_API_KEY}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
